### ISSUE TITLE
Contest registration

### ISSUE THREAD

**Issue by smikitky** [aiwolf/CompetitionInfrastructureDivision#1]
On August 14th, I sent an email from a certain Gmail address for registration in the infrastructure division, but I have not received a reply yet. Since today is the deadline, please allow me to indicate my intention to participate here for the record. 

**Project**: UTRAD Werewolf
**GitHub repository**: https://github.com/smikitky/utrad-werewolf
**Documentation**: https://utrad-werewolf-docs.netlify.app/

**Comment by AIWolfSharp** [comment]
I'm so sorry for not noticing your comment. 
The registration was successful, so I'll close this issue.
